// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Configuration: typeof import('./components/Configuration.vue')['default']
    DragPanel: typeof import('./components/DragPanel.vue')['default']
    Widget: typeof import('./components/Widget.vue')['default']
    WidgetList: typeof import('./components/WidgetList.vue')['default']
  }
}
